# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -r win-x64
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: ./bin/Release/net9.0-windows/win-x64/publish
  
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
  
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          publish/*.exe
          publish/*.pdb
        body: "Release ${{ github.run_number }} (${{ github.sha }})"
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "release-${{ github.run_number }}"
        name: "Release ${{ github.run_number }} (${{ github.sha }})"
        draft: false
        prerelease: false
